version: "2"
services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka:0.10.2.0
        environment:
            KAFKA_CREATE_TOPICS: "topic_1:1:1:compact,topic_2:1:1:compact"
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
            KAFKA_ADVERTISED_HOST_NAME: DOCKER_IP_HERE
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_LOG_RETENTION_HOURS: 1
            KAFKA_MESSAGE_MAX_BYTES: 10000000
            KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
            KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
            KAFKA_NUM_PARTITIONS: 2
            KAFKA_ZOOKEEPER_CONNECT: zk:2181
            KAFKA_DELETE_TOPIC_ENABLE: 'true'
            KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 1000
            JMX_PORT: 9999
        ports:
            - "9092:9092"
            - "9999:9999"
        links:
            - zookeeper:zk
    kafka-manager:
        image: sheepkiller/kafka-manager:latest
        ports:
            - "9000:9000"
        links:
            - zookeeper
            - kafka
        environment:
            ZK_HOSTS: zookeeper:2181
            APPLICATION_SECRET: letmein
            KM_ARGS: -Djava.net.preferIPv4Stack=true
    snowplow_collector:
        image: kafkasp:latest
        ports:
            - '8081:8081'
        links:
            - kafka
        volumes:
            - ./stream-collector/config/collector.conf:/etc/snowplow/collector.conf
